name: trivia-text-quiz
base: core20
version: '1.0.0'
summary: Text based trivia quiz. Questions from the Open Trivia Database
description: |
  This is a command line text base trivia quiz.  Questions are sourced
  from the Open Trivia Database in a user selectable category and difficulty.

confinement: strict
grade: stable

apps:
  trivia-text-quiz:
    command: bin/trivia-text-quiz
    plugs: [home,network-bind]
parts:
  trivia-text-quiz:
    plugin: python
    source: .
    stage-packages: [ncbi-blast+]